### PR TITLE
Feature/on point 019

### LINKED ISSUE #39: OnPoint-019 Support DarkMode
As a
User
I want to
use my App in dark mode
so that
everything on my phone is the same

### PR DESCRIPTION
**Pull request by muresangabriel-alexander**
Fixed visibility in dark mode
Added general dark mode support

### CODE REVIEW

**Comment by TheMatjaz** [comment]
Tested in light mode and dark mode: passing

**Comment by stefandivora** [comment]
all tests work in dark mode and light mode

**Review by elChango — APPROVED** [review]
all tests pass in dark and light mode
app works as expected

**Review by s1cent — APPROVED** [review]
LGTM

**Pull request merged**
