### PR TITLE
Feature/on point 003

### PR DESCRIPTION
**Pull request by muresangabriel-alexander**
Basic UI elemnets present and working. No program logic yet

### CODE REVIEW

**Comment by csskevin** [comment]
Unfortunately the tests fails in SidebarTest in `checkSidebarClickable`
Screen Shot 2021-05-05 at 12 06 44

**Comment by stefandivora** [comment]
works on my machine

**Comment by muresangabriel-alexander** [comment]
Works fine now

**Review by csskevin — APPROVED** [review]
- All tests passed.
- Feature works as expected.

**Review by s1cent — APPROVED** [review]
everything passes

**Pull request merged**
