### PR TITLE
OnPoint-M1 Pairing Matrix [SD]

### PR DESCRIPTION
**Pull request by stefandivora**
Pairing Matrix for KW15

### CODE REVIEW

**Review by s1cent — DISMISSED** [review]

**Comment by stefandivora** [comment]
added KW17 matrix

**Comment by stefandivora** [comment]
added KW18 matrix

**Comment by stefandivora** [comment]
Integrated everything until release 1

**Review by csskevin — DISMISSED** [review]
Looks good for my side. Maybe everyone should check it on their own before merging.

**Review by TheMatjaz — DISMISSED** [review]
Matches with my hours 100%

**Pull request merged**
