### PR TITLE
Feature/on point 016

### LINKED ISSUE #18: OnPoint-016 Assignment Filtering
**As a**
User
**I want to**
Filter the Assignments (Done/Pending/Subject)
**so that**
I search for specific thing

**Acceptance Criteria:**
- filtering with buttons in the Overview of all the Assignments

### PR DESCRIPTION
**Pull request by muresangabriel-alexander**

### CODE REVIEW

**Review by s1cent — DISMISSED** [review]
All tests passed!

**Comment by csskevin** [comment]
- All tests passed

**Review by s1cent — APPROVED** [review]
LGTM

**Review by csskevin — APPROVED** [review]
All Tests passed

**Pull request merged**
